# Generated by Django 4.2.4 on 2023-08-28 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tvparser',
            name='title_text',
        ),
        migrations.AddField(
            model_name='tvparser',
            name='title_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
