# Generated by Django 4.2.4 on 2023-08-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogprogramlang',
            name='description',
        ),
        migrations.AddField(
            model_name='blogprogramlang',
            name='color',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='blogprogramlang',
            name='descriptions',
            field=models.TextField(null=True),
        ),
    ]
