# Generated by Django 4.2.4 on 2023-08-31 11:14

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.CharField(choices=[('Client', 'Client'), ('VipClient', 'VipClient'), ('BigBoss', 'BigBoss')], max_length=100)),
                ('phone_number', models.CharField(default=996, max_length=13)),
                ('age', models.PositiveIntegerField(default=18)),
                ('gender', models.CharField(choices=[('M', 'M'), ('Ж', 'Ж')], max_length=100)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
